version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      db:
         condition: service_healthy

    env_file:
      - ./server/.env
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "5173:80"
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Infinit1
      POSTGRES_DB: game_reviews
    volumes:
      - videogames_reviews_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
