apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port | default .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
