apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.database.service.type | default "ClusterIP" }}
  clusterIP: None   # keep headless for StatefulSet stable DNS
  selector:
    app: database
  ports:
    - name: db
      port: {{ .Values.database.service.port | default .Values.database.port }}
      targetPort: {{ .Values.database.port }}
