apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }} 
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port | default .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}      
